### PR TITLE
Add ability to parse new style user pages.

### LINKED ISSUE #19: RSS feed is empty for new-style twitter pages
Twitter is rolling out a new design, e.g.

https://twitter.com/atarchivebot (new style)
https://twitter.com/textfiles (new style)
https://twitter.com/patio11 (old style)
https://twitter.com/cursiveclojure (old style)

twitter-rss doesn't return any items in the RSS feed for new-style pages.

### PR DESCRIPTION
**Pull request by jparyani**
I ended up upgrading to BeautifulSoup4 in the process as well. The older BeautifulSoup3 package wasn't parsing attributes correctly for me, and I just thought it'd be easier to upgrade than deal with debugging what wasn't working in BeautifulSoup3. If upgrading BeautifulSoup is a deal breaker, let me know, and I'll try and re-write around its bugs. 

Fixes #19

### CODE REVIEW

**Comment by ivan** [comment]
This appears to be working for a new-style page, but for an old-style page, https://twitter.com/fogus, I see:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/twitterrss/twitter-rss/server.py", line 41, in feed_to_xml
    error = tweets.to_rss().encode('utf-8')
  File "/home/twitterrss/twitter-rss/twitter_rss.py", line 124, in to_rss
    items = list(map(lambda tweet: tweet.to_jinja2(), self.tweets))
  File "/home/twitterrss/twitter-rss/twitter_rss.py", line 124, in <lambda>
    items = list(map(lambda tweet: tweet.to_jinja2(), self.tweets))
  File "/home/twitterrss/twitter-rss/twitter_rss.py", line 72, in to_jinja2
    if config.PICS is True and self.get_pic() != None:
  File "/home/twitterrss/twitter-rss/twitter_rss.py", line 56, in get_pic
    content = requests.get(pic_url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 349, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 287, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 287, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 334, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 390, in parse_url
    raise LocationParseError("Failed to parse: %s" % url)
LocationParseError: Failed to parse: Failed to parse: <p class="js-tweet-text tweet-text">Um... I guess I have a thing for pyramids. <a class="twitter-timeline-link" data-pre-embedded="true" dir="ltr" href="http:
```

```
# dpkg -l | grep bs4
ii  python-bs4                          4.2.1-1ubuntu2                       all          error-tolerant HTML parser for Python
```

**Comment by jparyani** [comment]
Woops, I have never used `Pics=True` in config.py, so I never ran into this in my testing. Should be fixed now.

**Comment by ivan** [comment]
Everything is working great here now, thanks for doing this!

**Comment by Astalaseven** [comment]
No problem with upgrade to bs4. Thank you for your commits, I'm actually a bit busy with studies and haven't a lot of time to fix it, it's a good surprise to see it fixed!

**Pull request merged**
