### PR TITLE
config.DIR for rss-model.tpl + config.DIR in run.py + init.d script for debian

### PR DESCRIPTION
**Pull request by PoGo606**
Hello,

After another try... here is my pull request : 
- config.DIR was missing for rss-model.tpl path
- Error message changed when rss-model.tpl is not found
- Use config.DIR for binary path in run.py + change of python's binary name
- A init.d script I made to daemonize the server (working on Debian).

Cheers.

### CODE REVIEW

**Comment by PoGo606** [comment]
I'm running twitter-rss on Debian 7 with python2.6 and python2.7 installed.
And there is no such python2 binary but : `/usr/bin/python2.6` and `/usr/bin/python2.7`

I guess that the existence of `/usr/bin/python2` depends on the OS you are using...

**Comment by Astalaseven** [comment]
Ok, I will try to find a solution that will not impact python3 users!

**Comment by PoGo606** [comment]
I don't understrand... `rss-model.tpl` is at the same place as in your repository.
If it's related to the use of config.DIR in the path for `rss-model.tpl`, I had to add it, as if you don't run the server from it's directory (with the init.d script for example), this file is stated as missing.

**Comment by Astalaseven** [comment]
I understand now, after reading your init.d script: You put the twitter-rss directory into `/var/www/`, but it is not needed. For example, I run it in my home, and I only put the `user/` and `htag/` folders into `/var/www/twitter-rss`.

So, if someone does the same as me, the `config.DIR + rss-model.tpl` will point in `/var/www/twitter-rss`, where it is not. It needs a new variable in `config.py`, but not `DIR`. The installation directory and the "serve file" directory doens't need to be necessary the same.

I will look for a new variable and adapt the script in consequence :).

**Comment by PoGo606** [comment]
All right that makes sense !
Thank you in advance then :)

**Comment by PoGo606** [comment]
Spotted :)
You're welcome ! 

In which url did you find this problem ?

**Comment by Astalaseven** [comment]
I found it trying to create a feed. For example: https://wtf.roflcopter.fr/twitter-rss/user/framasoft.xml
In the source code: `<html><body><rss version="2.0"` and `</rss></body></html>`. 
Did you change the `rss-model.tpl`?

**Comment by PoGo606** [comment]
It was because of the ProxyHTML enforcing the HTML tag everywhere even for the XML data.
I had to change the configuration in order to exclude the xml files: 

```
ProxyPass /twitter-rss http://172.16.1.10:5000
    ProxyPassReverse /twitter-rss http://172.16.1.10:5000
    RewriteRule ^/twitter-rss$ twitter-rss/ [R]
    <LocationMatch ^/twitter-rss/(?!(user|htag)/.+\.xml)>
        ProxyHTMLEnable On
        ProxyHTMLDocType "<!DOCTYPE html>"
        ProxyHTMLURLMap / /twitter-rss/
        ProxyPassReverse /
        RequestHeader    unset  Accept-Encoding
    </LocationMatch>
```

**Pull request closed without merging**
