### PR TITLE
Improve docker image & documentation

### PR DESCRIPTION
**Pull request by djmaze**
Changed the Docker image to use the supervisord approach. Also added a fig configuration for building and some real instructions for usage.

### CODE REVIEW

**Comment by Astalaseven** [comment]
Hi !

I don't understand when you get the code, as you commented
`#RUN git clone git://github.com/Astalaseven/twitter-rss.git /home/asta/twitter-rss`

**Comment by djmaze** [comment]
Right, I should have explained that. The build uses the contents of the current directory (i.e. your checkout of twitter-rss) and adds that to the image.

I added a comment in the Dockerfile explaining this. Is it ok from your perspective?

**Comment by Astalaseven** [comment]
Ok I understand, Docker does not fetch the code on its own, the user needs to it himself.
Should it be not easier to directly fetch the code from Github? I'm not against the change but I don't see the usage of it…

Edit: I am not a Docker user, I hadn't understand your explanation. To use Docker, you first need to download the source of course, so it is not necessary to download it twice.

Thanks for your contribution!

**Comment by djmaze** [comment]
The idea is that the Dockerfile belongs to the repository. So the user checks out twitter-rss from Github which includes the Dockerfile. Then he can build the image from within the checked out repository. So it's:

``` bash
git clone git@github.com:Astalaseven/twitter-rss.git
cd twitter-rss
sudo docker build -t twitter-rss .
sudo docker run -d -p 5000:5000 twitter-rss
```

You can make changes to the code and even check out different branches or tags, and just run `docker build` again to build a different version. This way you can use the same Dockerfile for development of the app and for generating a production image. And the Dockerfile stays with the code, where it belongs. This is a widely deployed pattern when working with docker. 

For an easier install, you can just push your locally built image to the docker registry. [I already did that](https://index.docker.io/u/mazzolino/twitter-rss/). So a user does not need to checkout the code, he can just run:

``` bash
sudo docker run -d -p 5000:5000 mazzolino/twitter-rss
```

That would fetch the pre-built (trusted) image from the central docker registry and run that. We can document this shortcut, too, if you wish.

**Comment by Astalaseven** [comment]
Thank you for taking the time for this explanation, I better understand how Docker works!
I merged your commits :)

**Comment by djmaze** [comment]
Thx! You are welcome :)

**Pull request merged**
